@echo off

cd "C:\Users\LENOVO\Desktop\Repositorios\etl"
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 1
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 2
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 3
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 4
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 5
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 6
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 7
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 8
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 9
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 10
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 11
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 12
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 13
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 14
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 15
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 16
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 17
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 18
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 19
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 20
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 21
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 22
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 23
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 24
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 25
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 26
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 27
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 28
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 29
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 30
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 31
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 32
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 33
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 34
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 35
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 36
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 37
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 38
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 39
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 40
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 41
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 42
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 43
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 44
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 45
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 46
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 47
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 48
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 49
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 50
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 51
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 52
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 53
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 54
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 55
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 56
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 57
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 58
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 59
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 60
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 61
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 62
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 63
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 64
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 65
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 66
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 67
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 68
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 69
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 70
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 71
 "C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps\python.exe"  "C:\Users\LENOVO\Desktop\Repositorios\etl\run.py" -i 5 -o 72

pause