import src.hrplus_sftp.transform_functions as transform_functions
configs = {
    "employees": {
        "sharepoint_config_key": "hrplus_employees",
        "report_name": "Employee",
        "rename_cols": {
            "global_id":"global_id",
            "Empl_Id":"empl_id_counter",
            "Last_Name":"last_name",
            "First_Name":"first_name",
            "Other_Name":"other_name",
            "Fulltime_Parttime":"fulltime_parttime",
            "Drivers_Permit":"drivers_permit",
            "PNo":"pno",
            "Status_in_Position":"status_in_position",
            "Date_of_Birth":"date_of_birth",
            "EmplType_Code":"empltype_code",
            "Unit_Code":"unit_code",
            "Preferred_Name":"preferred_name",
            "Home_Telephone":"home_telephone",
            "Sex":"sex",
            "Phone_Extension":"phone_extension",
            "Marital_Status":"marital_status",
            "Date_Started":"date_started",
            "StatusType_Code":"statustype_code",
            "Date_Separated":"date_separated",
            "Inland_Revenue_Id":"inland_revenue_id",
            "National_Insurance_Id":"national_insurance_id",
            "National_Id":"national_id",
            "First_Passport_No":"first_passport_no",
            "Second_Passport_No":"second_passport_no",
            "Salutation":"salutation",
            "Religion_Code":"religion_code",
            "Nationality_Code":"nationality_code",
            "Shift_Worker":"shift_worker",
            "Address_Line_One":"address_line_one",
            "Address_Line_Two":"address_line_two",
            "Address_Line_Three":"address_line_three",
            "Department_Start_Date":"department_start_date",
            "Position_Start_Date":"position_start_date",
            "Prior_Name":"prior_name",
            "Disability":"disability",
            "First_Hire_Date":"first_hire_date",
            "Last_Hire_Date":"last_hire_date",
            "Requisition_No":"requisition_no",
            "Hired_By":"hired_by",
            "Hire_Reason":"hire_reason",
            "Hire_Source":"hire_source",
            "Adj_Hire_Reason":"adj_hire_reason",
            "Adj_Hire_Date":"adj_hire_date",
            "Seniority_Date":"seniority_date",
            "Adj_Seniority_Date":"adj_seniority_date",
            "Pno_Counter":"pno_counter",
            "Fax_Number":"fax_number",
            "Status_Extension_Date":"status_extension_date",
            "badge_number":"badge_number",
            "empl_class":"empl_class"
        },
        "date_cols": ["date_of_birth", "date_started", "date_separated", "department_start_date", "position_start_date", 
                      "first_hire_date", "last_hire_date", "adj_hire_date", "seniority_date", "adj_seniority_date", 
                      "status_extension_date"],
        "expected_cols": ["global_id", "Empl_Id", "Last_Name", "First_Name", "Other_Name", "Fulltime_Parttime", 
                          "Drivers_Permit", "PNo", "Status_in_Position", "Date_of_Birth", "EmplType_Code", "Unit_Code", 
                          "Preferred_Name", "Home_Telephone", "Sex", "Phone_Extension", "Marital_Status", "Date_Started", 
                          "StatusType_Code", "Date_Separated", "Inland_Revenue_Id", "National_Insurance_Id", "National_Id", 
                          "First_Passport_No", "Second_Passport_No", "Salutation", "Religion_Code", "Nationality_Code", "Shift_Worker", 
                          "Address_Line_One", "Address_Line_Two", "Address_Line_Three", "Department_Start_Date", "Position_Start_Date", 
                          "Prior_Name", "Disability", "First_Hire_Date", "Last_Hire_Date", "Requisition_No", "Hired_By", "Hire_Reason", 
                          "Hire_Source", "Adj_Hire_Reason", "Adj_Hire_Date", "Seniority_Date", "Adj_Seniority_Date", "Pno_Counter", 
                          "Fax_Number", "Status_Extension_Date", "badge_number", "empl_class"],
        "use_cols":["global_id", "Empl_Id", "Last_Name", "First_Name", "Other_Name", "Fulltime_Parttime", 
                          "Drivers_Permit", "PNo", "Status_in_Position", "Date_of_Birth", "EmplType_Code", "Unit_Code", 
                          "Preferred_Name", "Home_Telephone", "Sex", "Phone_Extension", "Marital_Status", "Date_Started", 
                          "StatusType_Code", "Date_Separated", "Inland_Revenue_Id", "National_Insurance_Id", "National_Id", 
                          "First_Passport_No", "Second_Passport_No", "Salutation", "Religion_Code", "Nationality_Code", "Shift_Worker", 
                          "Address_Line_One", "Address_Line_Two", "Address_Line_Three", "Department_Start_Date", "Position_Start_Date", 
                          "Prior_Name", "Disability", "First_Hire_Date", "Last_Hire_Date", "Requisition_No", "Hired_By", "Hire_Reason", 
                          "Hire_Source", "Adj_Hire_Reason", "Adj_Hire_Date", "Seniority_Date", "Adj_Seniority_Date", "Pno_Counter", 
                          "Fax_Number", "Status_Extension_Date", "badge_number", "empl_class"],
        "read_with_dtype": {
            "Empl_Id": str
        },
        "transform_fn":transform_functions.employee_transforms
    },
    "positions": {
        "report_name": "Positions",
        "rename_cols": {
            "PNo":"pno",
            "StaffType_Code":"stafftype_code",
            "Job_Code":"job_code",
            "Div_Code":"div_code",
            "Div_Name":"div_name",
            "Dept_Code":"dept_code",
            "Dept_Name":"dept_name",
            "Section_Code":"section_code",
            "Section_Name":"section_name",
            "Comp_Code":"comp_code",
            "Comp_Name":"comp_name",
            "Loc_Code":"loc_code",
            "approved_by":"approved_by",
            "Date_Created":"date_created",
            "Fill_Date":"fill_date",
            "StatusType_Code":"statustype_code",
            "approval_date":"approval_date",
            "Comments":"comments",
            "Full_Time":"full_time",
            "Executive":"executive",
            "effective_date":"effective_date",
            "pay_group":"pay_group"
        },
        "date_cols": ["fill_date", "approval_date", "effective_date"],
        "use_cols": ["PNo","StaffType_Code","Job_Code","Div_Code","Div_Name","Dept_Code","Dept_Name","Section_Code",
                          "Section_Name","Comp_Code","Comp_Name","Loc_Code","approved_by","Date_Created","Fill_Date",
                          "StatusType_Code","approval_date","Comments","Full_Time","Executive","effective_date","pay_group"],
        "sharepoint_config_key": "hrplus_positions",
        "read_with_dtype": None,
        "transform_fn":transform_functions.position_transforms        
    },
    "time_sheet": {
        "report_name": "EmpTimeClockTimesheet",
        "date_cols": ["dayWorked", "DateIn1", "DateOut1", "DateIn2", "DateOut2", "DateIn3", "DateOut3", "lDateOut1", "lDateIn1", "lDateOut2", "lDateOut3", "lDateIn2", "lDateIn3"],
        "time_cols": ["timeIn1", "timeOut1", "timeIn2", "timeOut2", "timeIn3", "timeOut3", "lTimeIn1", "lTimeOut1", "lTimeIn2", "lTimeOut2", "lTimeIn3", "lTimeOut3"],
        "use_cols": ["timesheetId", "pay_group", "cycle_no", "pay_year", "dayWorked", "empl_id", "callOut", "shift_Code", "timeIn1", 
                     "timeOut1", "timeIn2", "timeOut2", "timeIn3", "timeOut3", "totalHours", "projectCode", "projectPhaseCode", 
                     "ConditionCode", "ReasonCode", "User_Code", "lTimeIn1", "lTimeOut1", "lTimeIn2", "lTimeOut2", "lTimeIn3", 
                     "lTimeOut3", "approved", "paytype_rate", "shift_type", "DateIn1", "DateOut1", "DateIn2", "DateOut2", "DateIn3", 
                     "DateOut3", "lDateOut1", "lDateIn1", "lDateOut2", "lDateOut3", "lDateIn2", "lDateIn3"],
        "sharepoint_config_key": "hrplus_timesheet",
        "read_with_dtype":
            {
                "empl_id": str
            },
        "transform_fn":transform_functions.timesheet_transform  
    },
    "time_sheet_arc": {
        "report_name": "EmpTimeClockTimesheet_Arc",
        "date_cols": ["dayWorked", "DateIn1", "DateOut1", "DateIn2", "DateOut2", "DateIn3", "DateOut3", "lDateOut1", "lDateIn1", "lDateOut2", "lDateOut3", "lDateIn2", "lDateIn3"],
        "time_cols": ["timeIn1", "timeOut1", "timeIn2", "timeOut2", "timeIn3", "timeOut3", "lTimeIn1", "lTimeOut1", "lTimeIn2", "lTimeOut2", "lTimeIn3", "lTimeOut3"],
        "use_cols": ["timesheetId", "pay_group", "cycle_no", "pay_year", "dayWorked", "empl_id", "callOut", "shift_Code", "timeIn1", 
                     "timeOut1", "timeIn2", "timeOut2", "timeIn3", "timeOut3", "totalHours", "projectCode", "projectPhaseCode", 
                     "ConditionCode", "ReasonCode", "User_Code", "lTimeIn1", "lTimeOut1", "lTimeIn2", "lTimeOut2", "lTimeIn3", 
                     "lTimeOut3", "approved", "paytype_rate", "shift_type", "DateIn1", "DateOut1", "DateIn2", "DateOut2", "DateIn3", 
                     "DateOut3", "lDateOut1", "lDateIn1", "lDateOut2", "lDateOut3", "lDateIn2", "lDateIn3"],
        "sharepoint_config_key": "hrplus_timesheet",
        "read_with_dtype":
            {
                "empl_id": str
            },
        "transform_fn":transform_functions.timesheet_arc_transform  
    },
    "emp_email":{
        "report_name": "EmpEmail",
        "use_cols": ["Empl_Id", "Address", "pager", "mobile",
                    "counter", "primaryEmailAddress", "usePrimaryEmail",
                    "workEmailAddress", "personalMobile1", "personalMobile2",
                    "companyMobile"],
        "rename_cols": {'Empl_Id': 'empl_id',
                            'Address': 'address',
                            'pager': 'pager',
                            'mobile': 'mobile',
                            'counter': 'counter',
                            'primaryEmailAddress': 'primaryemailaddress',
                            'usePrimaryEmail': 'useprimaryemail',
                            'workEmailAddress': 'workemailaddress',
                            'personalMobile1': 'personalmobile1',
                            'personalMobile2': 'personalmobile2',
                            'companyMobile': 'companymobile'},
        "sharepoint_config_key": "hrplus_empemail",
        "read_with_dtype": {"Empl_Id": str},
        "transform_fn": transform_functions.empemail_transforms
    },
    "hri_users":{
        "report_name": "hri_users",
        "date_cols": ["expiry_date", "account_end_date"],
        "use_cols": ["expiry_date", "empl_id", "user_code", "MyLanguage", "Email", "account_end_date"],
        "rename_cols": {'Email': 'email'},
        "sharepoint_config_key": "hrplus_hri_users",
        "read_with_dtype": {"empl_id": str},
        "transform_fn": transform_functions.hriusers_transforms
    },
    "reports_to": {
        "sharepoint_config_key": "hrplus_reportsto",
        "report_name": "Reports_To",
        "rename_cols": {
            "Assistant": "assistant",
            "PNo": "pno",
            "Reportsto_PNo": "reportsto_pno",
            "Supervisor_Type": "supervisor_type"
        },
        "use_cols": ['Assistant', 'PNo', 'Reportsto_PNo', 'Supervisor_Type'],
        "read_with_dtype": None,
        "transform_fn": transform_functions.reportsto_transforms
    }
}