import src.capacity_planning.functions.live_excel_functions as functions
import numpy as np

configs = {
    "planned_training_template": {
        "read_with_dtype": {
                "Fill %": "float64",
                "Show %": "float64",
                "FTE Target": object,
                "HTD": object,
                "Showed": object,
                "RD": object,
                "Manual": object,
                "Start Date": "datetime64",
                "OJT Date": object,
                "Roster Submit": object,
                "Alignment": "str",
                "Class Status": "str",
                "STATUS": "str",
                "ACCOUNT": "str",
                "BATCH #": "str",
                "Site": "str",
                "ACCOUNT2": "str"
        },
        "info_transform_function": {
            "df_handling": {
                "order_columns": [
                    "Alignment",
                    "Class Status",
                    "STATUS",
                    "ACCOUNT",
                    "BATCH #",
                    "FTE Target",
                    "HTD",
                    "Showed",
                    "Fill %",
                    "Show %",
                    "Start Date",
                    "OJT Date",
                    "Roster Submit",
                    "Site",
                    "ACCOUNT2",
                    "RD",
                    "Manual"
                ],
                "rename_columns": {
                    "Fill %": "fill",
                    "Show %": "show",
                    "FTE Target": "fte_target",
                    "HTD": "htd",
                    "Showed": "showed",
                    "RD": "rd",
                    "Manual": "manual",
                    "Start Date": "start_date",
                    "OJT Date": "ojt_date",
                    "Roster Submit": "roster_submit",
                    "Alignment": "alignment",
                    "Class Status": "class_status",
                    "STATUS": "status",
                    "ACCOUNT": "account",
                    "BATCH #": "batch",
                    "Site": "site",
                    "ACCOUNT2": "account2"
                },
                "validate_float_columns": [
                    "fill",
                    "show"
                ],
                "validate_int_columns": [
                    "fte_target",
                    "htd",
                    "showed",
                    "rd",
                    "manual"
                ],
                "validate_date_columns": {
                    "columns": [
                        "start_date",
                        #"ojt_date",
                        "roster_submit"
                    ],
                    "parameters": {
                        "date_format": "%m/%d/%Y"
                    }
                },
                "validate_text_columns": [
                    "alignment",
                    "class_status",
                    "status",
                    "account",
                    "batch",
                    "site",
                    "account2"
                ]
            }
        },
        "transform_function": functions.transforms_function_planned_training_template
    },
    "consolidated_cap_plan_new_details": {
        "read_with_dtype": {
            "Shrink": "float64",
            "Attr": "float64",
            "Training Attr": "float64",
            "Production FTE-required": "float64",
            "Production FTE": "float64",
            "Production FTE2-O/U": "float64",
            "Production HC-required": "float64",
            "Production HC-planned": "float64",
            "Production HC-O/U": "float64",
            "Reduction attrition": "float64",
            "OM -planned": "float64",
            "Supervisors-planned": "float64",
            "Supervisors-O/U": "float64",
            "RTA-required": "float64",
            "RTA-planned": "float64",
            "WFA-planned": "float64",
            "QA-planned": "float64",
            "QA-O/U": "float64",
            "Trainers-planned": "float64",
            "Required Seats KGN": "float64",
            "Required Seats UWI\n": "float64",
            "Required Seats KGN BOT": "float64",
            "Required Seats MBJ": "float64",
            "Required Seats Chalmers": "float64",
            "Required Seats SLU\n": "float64",
            "Required Seats BAH": "float64",
            "Required Seats GUY": "float64",
            "Required Seats HON\n": "float64",
            "TSeats Available KGN": "float64",
            "TSeats Available UWI": "float64",
            "TSeats Available KGN BOT": "float64",
            "TSeats Available MBJ": "float64",
            "TSeats Available Chalmers": "float64",
            "TSeats Available SLU": "float64",
            "TSeats Available BAH": "float64",
            "TSeats Available GUY": "float64",
            "TSeats Available HON": "float64",
            "RSeats vs APCs KGN": "float64",
            "RSeats vs APCs KGN BOT": "float64",
            "RSeats vs APCs MBJ": "float64",
            "RSeats vs APCs Chalmers": "float64",
            "RSeats vs APCs SLU": "float64",
            "RSeats vs APCs BAH": "float64",
            "RSeats vs APCs GUY": "float64",
            "RSeats vs APCs HON": "float64",
            "RSeats from scheduling KGN": "float64",
            "RSeats from scheduling UWI\n": "float64",
            "RSeats from scheduling KGN BOT": "float64",
            "RSeats from scheduling MBJ": "float64",
            "RSeats from scheduling SLU": "float64",
            "RSeats from scheduling BAH": "float64",
            "RSeats from scheduling GUY": "float64",
            "RSeats from scheduling HON": "float64",
            "Total PC Var2": "float64",
            "Id": "int64",
            "Pre Planned Training HC": object,
            "Actual headcount -HC": "int64",
            "Actual headcount-attr": "int64",
            "OJT Headcount": "int64",
            "OJT - FTE": "int64",
            "Reduction moves": "int64",
            "OM -required": "int64",
            "OM-O/U": "int64",
            "Supervisors-required": "int64",
            "RTA-O/U": "int64",
            "WFA-required": "int64",
            "WFA-O/U": "int64",
            "QA- required": "int64",
            "Trainers-required": "int64",
            "Trainers-O/U": "int64",
            "Required Seats WAH": "int64",
            "Required Seats JEF": "int64",
            "Seating In-Use WAH": "int64",
            "Seating In-Use KGN": "int64",
            "Seating In-Use UWI\n": "int64",
            "Seating In-Use KGN BOT": "int64",
            "Seating In-Use MBJ": "int64",
            "Seating In-Use Chalmers": object,
            "Seating In-Use SLU\n": "int64",
            "Seating In-Use BAH": "int64",
            "Seating In-Use GUY": "int64",
            "Seating In-Use HON\n": "int64",
            "Seating In-Use JEF": "int64",
            "TSeats Available WAH": "int64",
            "TSeats Available JEF": "int64",
            "Total PCs Available WAH": "int64",
            "Total PCs Available KGN": "int64",
            "Total PCs Available UWI": "int64",
            "Total PCs Available KGN BOT": "int64",
            "Total PCs Available MBJ": "int64",
            "Total PCs Available Chalmers": object,
            "Total PCs Available SLU": "int64",
            "Total PCs Available BAH": "int64",
            "Total PCs Available GUY": "int64",
            "Total PCs Available HON": "int64",
            "Total PCs Available JEF": "int64",
            "RSeats vs APCs WAH": "int64",
            "RSeats vs APCs UWI": "int64",
            "RSeats vs APCs JEF": "int64",
            "RSeats from scheduling WAH\n": "int64",
            "RSeats from scheduling Chalmers": "int64",
            "RSeats from scheduling JEF": "int64",
            "Date ": "datetime64",
            "Unnamed: 0": "str",
            "business units": "str",
            "Site": "str",
            "Pre Planned Training category": "str",
            "Occupancy":"float64"
        },
        "info_transform_function": {
            "df_handling": {
                "order_columns": [
                    "Unnamed: 0",
                    "Id",
                    "business units",
                    "Site",
                    "Date ",
                    "Shrink",
                    "Attr",
                    "Training Attr",
                    "Pre Planned Training HC",
                    "Pre Planned Training category",
                    "Actual headcount -HC",
                    "Actual headcount-attr",
                    "OJT Headcount",
                    "OJT - FTE",
                    "Production FTE-required",
                    "Production FTE",
                    "Production FTE2-O/U",
                    "Production HC-required",
                    "Production HC-planned",
                    "Production HC-O/U",
                    "Reduction attrition",
                    "Reduction moves",
                    "OM -required",
                    "OM -planned",
                    "OM-O/U",
                    "Supervisors-required",
                    "Supervisors-planned",
                    "Supervisors-O/U",
                    "RTA-required",
                    "RTA-planned",
                    "RTA-O/U",
                    "WFA-required",
                    "WFA-planned",
                    "WFA-O/U",
                    "QA- required",
                    "QA-planned",
                    "QA-O/U",
                    "Trainers-required",
                    "Trainers-planned",
                    "Trainers-O/U",
                    "Required Seats WAH",
                    "Required Seats KGN",
                    "Required Seats UWI\n",
                    "Required Seats KGN BOT",
                    "Required Seats MBJ",
                    "Required Seats Chalmers",
                    "Required Seats SLU\n",
                    "Required Seats BAH",
                    "Required Seats GUY",
                    "Required Seats HON\n",
                    "Required Seats JEF",
                    "Seating In-Use WAH",
                    "Seating In-Use KGN",
                    "Seating In-Use UWI\n",
                    "Seating In-Use KGN BOT",
                    "Seating In-Use MBJ",
                    "Seating In-Use Chalmers",
                    "Seating In-Use SLU\n",
                    "Seating In-Use BAH",
                    "Seating In-Use GUY",
                    "Seating In-Use HON\n",
                    "Seating In-Use JEF",
                    "TSeats Available WAH",
                    "TSeats Available KGN",
                    "TSeats Available UWI",
                    "TSeats Available KGN BOT",
                    "TSeats Available MBJ",
                    "TSeats Available Chalmers",
                    "TSeats Available SLU",
                    "TSeats Available BAH",
                    "TSeats Available GUY",
                    "TSeats Available HON",
                    "TSeats Available JEF",
                    "Total PCs Available WAH",
                    "Total PCs Available KGN",
                    "Total PCs Available UWI",
                    "Total PCs Available KGN BOT",
                    "Total PCs Available MBJ",
                    "Total PCs Available Chalmers",
                    "Total PCs Available SLU",
                    "Total PCs Available BAH",
                    "Total PCs Available GUY",
                    "Total PCs Available HON",
                    "Total PCs Available JEF",
                    "RSeats vs APCs WAH",
                    "RSeats vs APCs KGN",
                    "RSeats vs APCs UWI",
                    "RSeats vs APCs KGN BOT",
                    "RSeats vs APCs MBJ",
                    "RSeats vs APCs Chalmers",
                    "RSeats vs APCs SLU",
                    "RSeats vs APCs BAH",
                    "RSeats vs APCs GUY",
                    "RSeats vs APCs HON",
                    "RSeats vs APCs JEF",
                    "RSeats from scheduling WAH\n",
                    "RSeats from scheduling KGN",
                    "RSeats from scheduling UWI\n",
                    "RSeats from scheduling KGN BOT",
                    "RSeats from scheduling MBJ",
                    "RSeats from scheduling Chalmers",
                    "RSeats from scheduling SLU",
                    "RSeats from scheduling BAH",
                    "RSeats from scheduling GUY",
                    "RSeats from scheduling HON",
                    "RSeats from scheduling JEF",
                    "Total PC Var2",
                    "Occupancy"
                ],
                "rename_columns": {
                    "Shrink": "shrink",
                    "Attr": "attr",
                    "Training Attr": "training_attr",
                    "Production FTE-required": "production_fte_required",
                    "Production FTE": "production_fte",
                    "Production FTE2-O/U": "production_fte2_o_u",
                    "Production HC-required": "production_hc_required",
                    "Production HC-planned": "production_hc_planned",
                    "Production HC-O/U": "production_hc_o_u",
                    "Reduction attrition": "reduction_attrition",
                    "OM -planned": "om_planned",
                    "Supervisors-planned": "supervisors_planned",
                    "Supervisors-O/U": "supervisors_o_u",
                    "RTA-required": "rta_required",
                    "RTA-planned": "rta_planned",
                    "WFA-planned": "wfa_planned",
                    "QA-planned": "qa_planned",
                    "QA-O/U": "qa_o_u",
                    "Trainers-planned": "trainers_planned",
                    "Required Seats KGN": "required_seats_kgn",
                    "Required Seats UWI\n": "required_seats_uwi",
                    "Required Seats KGN BOT": "required_seats_kgn_bot",
                    "Required Seats MBJ": "required_seats_mbj",
                    "Required Seats Chalmers": "required_seats_chalmers",
                    "Required Seats SLU\n": "required_seats_slu",
                    "Required Seats BAH": "required_seats_bah",
                    "Required Seats GUY": "required_seats_guy",
                    "Required Seats HON\n": "required_seats_hon",
                    "TSeats Available KGN": "tseats_available_kgn",
                    "TSeats Available UWI": "tseats_available_uwi",
                    "TSeats Available KGN BOT": "tseats_available_kgn_bot",
                    "TSeats Available MBJ": "tseats_available_mbj",
                    "TSeats Available Chalmers": "tseats_available_chalmers",
                    "TSeats Available SLU": "tseats_available_slu",
                    "TSeats Available BAH": "tseats_available_bah",
                    "TSeats Available GUY": "tseats_available_guy",
                    "TSeats Available HON": "tseats_available_hon",
                    "RSeats vs APCs KGN": "rseats_vs_apcs_kgn",
                    "RSeats vs APCs KGN BOT": "rseats_vs_apcs_kgn_bot",
                    "RSeats vs APCs MBJ": "rseats_vs_apcs_mbj",
                    "RSeats vs APCs Chalmers": "rseats_vs_apcs_chalmers",
                    "RSeats vs APCs SLU": "rseats_vs_apcs_slu",
                    "RSeats vs APCs BAH": "rseats_vs_apcs_bah",
                    "RSeats vs APCs GUY": "rseats_vs_apcs_guy",
                    "RSeats vs APCs HON": "rseats_vs_apcs_hon",
                    "RSeats from scheduling KGN": "rseats_from_scheduling_kgn",
                    "RSeats from scheduling UWI\n": "rseats_from_scheduling_uwi",
                    "RSeats from scheduling KGN BOT": "rseats_from_scheduling_kgn_bot",
                    "RSeats from scheduling MBJ": "rseats_from_scheduling_mbj",
                    "RSeats from scheduling SLU": "rseats_from_scheduling_slu",
                    "RSeats from scheduling BAH": "rseats_from_scheduling_bah",
                    "RSeats from scheduling GUY": "rseats_from_scheduling_guy",
                    "RSeats from scheduling HON": "rseats_from_scheduling_hon",
                    "Total PC Var2": "total_pc_var2",
                    "Id": "id",
                    "Pre Planned Training HC": "pre_planned_training_hc",
                    "Actual headcount -HC": "actual_headcount_hc",
                    "Actual headcount-attr": "actual_headcount_attr",
                    "OJT Headcount": "ojt_headcount",
                    "OJT - FTE": "ojt_fte",
                    "Reduction moves": "reduction_moves",
                    "OM -required": "om_required",
                    "OM-O/U": "om_o_u",
                    "Supervisors-required": "supervisors_required",
                    "RTA-O/U": "rta_o_u",
                    "WFA-required": "wfa_required",
                    "WFA-O/U": "wfa_o_u",
                    "QA- required": "qa_required",
                    "Trainers-required": "trainers_required",
                    "Trainers-O/U": "trainers_o_u",
                    "Required Seats WAH": "required_seats_wah",
                    "Required Seats JEF": "required_seats_jef",
                    "Seating In-Use WAH": "seating_in_use_wah",
                    "Seating In-Use KGN": "seating_in_use_kgn",
                    "Seating In-Use UWI\n": "seating_in_use_uwi",
                    "Seating In-Use KGN BOT": "seating_in_use_kgn_bot",
                    "Seating In-Use MBJ": "seating_in_use_mbj",
                    "Seating In-Use Chalmers": "seating_in_use_chalmers",
                    "Seating In-Use SLU\n": "seating_in_use_slu",
                    "Seating In-Use BAH": "seating_in_use_bah",
                    "Seating In-Use GUY": "seating_in_use_guy",
                    "Seating In-Use HON\n": "seating_in_use_hon",
                    "Seating In-Use JEF": "seating_in_use_jef",
                    "TSeats Available WAH": "tseats_available_wah",
                    "TSeats Available JEF": "tseats_available_jef",
                    "Total PCs Available WAH": "total_pcs_available_wah",
                    "Total PCs Available KGN": "total_pcs_available_kgn",
                    "Total PCs Available UWI": "total_pcs_available_uwi",
                    "Total PCs Available KGN BOT": "total_pcs_available_kgn_bot",
                    "Total PCs Available MBJ": "total_pcs_available_mbj",
                    "Total PCs Available Chalmers": "total_pcs_available_chalmers",
                    "Total PCs Available SLU": "total_pcs_available_slu",
                    "Total PCs Available BAH": "total_pcs_available_bah",
                    "Total PCs Available GUY": "total_pcs_available_guy",
                    "Total PCs Available HON": "total_pcs_available_hon",
                    "Total PCs Available JEF": "total_pcs_available_jef",
                    "RSeats vs APCs WAH": "rseats_vs_apcs_wah",
                    "RSeats vs APCs UWI": "rseats_vs_apcs_uwi",
                    "RSeats vs APCs JEF": "rseats_vs_apcs_jef",
                    "RSeats from scheduling WAH\n": "rseats_from_scheduling_wah",
                    "RSeats from scheduling Chalmers": "rseats_from_scheduling_chalmers",
                    "RSeats from scheduling JEF": "rseats_from_scheduling_jef",
                    "Date ": "date",
                    "Unnamed: 0": "unnamed:_0",
                    "business units": "business_units",
                    "Site": "site",
                    "Pre Planned Training category": "pre_planned_training_category",
                    "Occupancy":"occupancy"
                },
                "validate_float_columns": [
                    "shrink",
                    "attr",
                    "training_attr",
                    "production_fte_required",
                    "production_fte",
                    "production_fte2_o_u",
                    "production_hc_required",
                    "production_hc_planned",
                    "production_hc_o_u",
                    "reduction_attrition",
                    "om_planned",
                    "supervisors_planned",
                    "supervisors_o_u",
                    "rta_required",
                    "rta_planned",
                    "wfa_planned",
                    "qa_planned",
                    "qa_o_u",
                    "trainers_planned",
                    "required_seats_kgn",
                    "required_seats_uwi",
                    "required_seats_kgn_bot",
                    "required_seats_mbj",
                    "required_seats_chalmers",
                    "required_seats_slu",
                    "required_seats_bah",
                    "required_seats_guy",
                    "required_seats_hon",
                    "tseats_available_kgn",
                    "tseats_available_uwi",
                    "tseats_available_kgn_bot",
                    "tseats_available_mbj",
                    "tseats_available_chalmers",
                    "tseats_available_slu",
                    "tseats_available_bah",
                    "tseats_available_guy",
                    "tseats_available_hon",
                    "rseats_vs_apcs_kgn",
                    "rseats_vs_apcs_kgn_bot",
                    "rseats_vs_apcs_mbj",
                    "rseats_vs_apcs_chalmers",
                    "rseats_vs_apcs_slu",
                    "rseats_vs_apcs_bah",
                    "rseats_vs_apcs_guy",
                    "rseats_vs_apcs_hon",
                    "rseats_from_scheduling_kgn",
                    "rseats_from_scheduling_uwi",
                    "rseats_from_scheduling_kgn_bot",
                    "rseats_from_scheduling_mbj",
                    "rseats_from_scheduling_slu",
                    "rseats_from_scheduling_bah",
                    "rseats_from_scheduling_guy",
                    "rseats_from_scheduling_hon",
                    "total_pc_var2",
                    "occupancy"
                ],
                "validate_int_columns": [
                    "id",
                    "pre_planned_training_hc",
                    "actual_headcount_hc",
                    "actual_headcount_attr",
                    "ojt_headcount",
                    "ojt_fte",
                    "reduction_moves",
                    "om_required",
                    "om_o_u",
                    "supervisors_required",
                    "rta_o_u",
                    "wfa_required",
                    "wfa_o_u",
                    "qa_required",
                    "trainers_required",
                    "trainers_o_u",
                    "required_seats_wah",
                    "required_seats_jef",
                    "seating_in_use_wah",
                    "seating_in_use_kgn",
                    "seating_in_use_uwi",
                    "seating_in_use_kgn_bot",
                    "seating_in_use_mbj",
                    "seating_in_use_chalmers",
                    "seating_in_use_slu",
                    "seating_in_use_bah",
                    "seating_in_use_guy",
                    "seating_in_use_hon",
                    "seating_in_use_jef",
                    "tseats_available_wah",
                    "tseats_available_jef",
                    "total_pcs_available_wah",
                    "total_pcs_available_kgn",
                    "total_pcs_available_uwi",
                    "total_pcs_available_kgn_bot",
                    "total_pcs_available_mbj",
                    "total_pcs_available_chalmers",
                    "total_pcs_available_slu",
                    "total_pcs_available_bah",
                    "total_pcs_available_guy",
                    "total_pcs_available_hon",
                    "total_pcs_available_jef",
                    "rseats_vs_apcs_wah",
                    "rseats_vs_apcs_uwi",
                    "rseats_vs_apcs_jef",
                    "rseats_from_scheduling_wah",
                    "rseats_from_scheduling_chalmers",
                    "rseats_from_scheduling_jef"
                ],
                "validate_date_columns": {
                    "columns": [
                        "date"
                    ],
                    "parameters": {
                        "date_format": "%m/%d/%Y"
                    }
                },
                "validate_text_columns": [
                    "unnamed:_0",
                    "business_units",
                    "site",
                    "pre_planned_training_category"
                ]
            }
        },
        "transform_function":  functions.transforms_function_consolidated_cap_plan_new_details
    },
    "consolidated_cap_plan_hiring_details":{
        "read_with_dtype": {
            "hiring": "float64",
            "date": "datetime64",
            "Category": "str",
            "Sites": "str",
            "BUs": "str"
        },
        "info_transform_function": {
            "df_handling": {
                "order_columns": [
                    "Category",
                    "Sites",
                    "BUs",
                    "date",
                    "hiring"
                ],
                "rename_columns": {
                    "Category": "category",
                    "Sites": "site",
                    "BUs": "bus"
                },
                "validate_int_columns": [
                    "hiring"
                ],
                "validate_date_columns": {
                    "columns": [
                        "date"
                    ],
                    "parameters": {
                        "date_format": "%m/%d/%Y"
                    }
                },
                "validate_text_columns": [
                    "category",
                    "site",
                    "bus"
                ]
            }
        },
        "transform_function":  functions.transforms_function_consolidated_cap_plan_hiring_details
    }
}