from datetime import datetime as dt
from datetime import timedelta

# Dates used as parameters for the queries. Download the last 45 days.
now = dt.now().date()
start_date = now - timedelta(days=45)
end_date = now - timedelta(days=1)

configs = {
	"employees":{
		"destination_schema": "hrmaster",
		"destination_table": "employees",
		"params": None,
		"query": """
			SELECT employee_id::text AS legacy_id,
			first_name,
			last_name,
			date_birth,
			national_id_number,
			hired_date,
			separation_date,
			national_id_document,
			status,
			direct_report_id,
			direct_report_name,
			hiring_comments,
			employment_scheme,
			contract_signed,
			added_payroll,
			is_remote,
			personal_email,
			work_email,
			address,
			phone_number,
			nis,
			nis_name,
			tin,
			number_kids,
			badge_type,
			lob_id,
			client_id,
			lob_name,
			client_name,
			contract_status,
			country,
			title_id,
			title_name,
			department_id,
			department_name,
			gender,
			language,
			wave,
			tenure_days,
			insurance_premium,
			insurance_effective_date,
			insurance_policy_number,
			insurance_coverage,
			insurance_status,
			full_name
		FROM hrmaster.hr_employee_database
		"""
	},
	"attrition":{
		"destination_schema": "hrmaster",
		"destination_table": "attrition",
		"params": None,
		"query": """
			SELECT emerge_id::text as legacy_id,
			full_name,
			first_name,
			last_name,
			status,
			client,
			line_business,
			employee_title,
			direct_report,
			hired_date,
			notice_date,
			separation_date,
			date_birth,
			wave,
			country,
			separation_type,
			separation_reason,
			separation_phase,
			breached_kpi,
			comments,
			is_rehireable,
			certified_by,
			client_portal_termination,
			completed_exit_interview,
			department_name,
			gender
		FROM hrmaster.hr_attrition
		"""
	},
	"glb_external_qa_audit_leasing":{
		"destination_schema": "anyone_home",
		"destination_table": "glb_external_qa_audit_leasing",
		"params": None,
		"query": """
			SELECT 
				DATE(shopcompleteddate) AS shop_completed_date,
				agentname AS agent_name,
				shop_id AS shop_sfid,
				account,
				property,
				supervisor,
				shopscore AS shop_score,
				shopcreateddate AS shop_created_date,
				coaching_completed_datetime AS coaching_completed_datetime,
				case_service_request_created_date,
				shopcategory AS shop_category,
				coaching_required,
				coachingcompleted AS coaching_completed,
				supervisor_coaching_completed,
				case_status,
				download_link,
				submitters_notes,
				coaching_notes,
				resolvers_notes,
				origin,
				service_request_pop,
				shopcompleteddate AS shop_completed_datetime,
				atfaultforpop AS at_fault_for_pop,
				qa_form_name,
				qa_reviewer,
				call_skill,
				call_duration,
				supervisor_name,
				team_lead_1,
				team_lead_2,
				grader_notes,
				prospect_info_completed,
				first_name,
				last_name,
				phone_number,
				email,
				professional,
				call_ending,
				care,
				outstanding_shop,
				case_creation_datetime,
				bedandbath,
				pets,
				reason_for_moving,
				floorplan_of_interest,
				rent_range,
				move_in,
				building_value,
				no_of_occupants,
				attempt_showing,
				qualification_policies,
				engaging_rapport,
				notes,
				navigation,
				accuracy
			FROM anyone_home.qa_external_leasing_audit
		"""
	},
	"glb_external_qa_maintenance":{
		"destination_schema": "anyone_home",
		"destination_table": "glb_external_qa_maintenance",
		"params": None,
		"query": """
			SELECT 
				DATE(shopcompleteddate) AS shop_completed_date,
				agentname AS agent_name,
				shopscore AS shop_score,
				supervisor,
				qa_reviewer,
				shop_id AS shop_sfid,
				account,
				property,
				shopcreateddate AS shop_created_date,
				shopcompleteddate AS shop_completed_datetime,
				coachingcompleteddate_time AS coaching_completed_datetime,
				case_servicerequestcreateddate AS case_service_request_created_date,
				shopcategory AS shop_category ,
				coaching_required,
				coachingcompleted AS coaching_completed,
				supervisor_coaching_completed,
				case_status,
				download_link,
				submitters_notes,
				coaching_notes,
				resolvers_notes,
				origin,
				service_request_pop,
				atfaultforpop AS at_fault_for_pop,
				qa_form_name,
				call_skill,
				call_duration,
				supervisor_name,
				team_lead_1,
				team_lead_2,
				grader_notes,
				prospect_info_completed,
				first_name,
				last_name,
				phone_number,
				email,
				building_value AS professional,
				call_ending,
				care,
				outstanding_shop,
				case_creation_datetime,
				property_unit_needing_service,
				room_area_impacted,
				sr_type,
				permission_to_enter,
				entry_info,
				troubleshooting,
				empathy,
				navigation_accuracy,
				work_order_notes
			FROM anyone_home.qa_external_maintenance
		"""
	}
}